### PR TITLE
Fix linting issues with single/double quotes

### PR DESCRIPTION
**Pull request by dan-knight**
- [X] I have read the [code review guidelines](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [X] The name of the branch is meaningful and well formatted following the [standards](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List), using \[AD_username (or 5 letters of AD if AD is too long)-\[brief_description_of_branch].

- [X] I have set up or verified the branch protection rule following the [github standards](https://confluence.mednet.ucla.edu/pages/viewpage.action?spaceKey=BOUTROSLAB&title=GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

- [X] I have added the changes included in this pull request to `NEWS` under the next release version or unreleased, and updated the date.

- [X] I have updated the version number in `metadata.yaml` and `DESCRIPTION`.

- [X] Both `R CMD build` and `R CMD check` run successfully.

Only fixes R lintr issues related to quotation marks - nothing else. Also removed old inst directory, as it had many double quotes and is no longer used for testing.

## Testing Results
```
R CMD check
```
### Output
```
* using log directory ‘/usr/src/app/VennDiagram.Rcheck’
* using R Under development (unstable) (2021-09-19 r80937)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘VennDiagram/DESCRIPTION’ ... OK
* checking extension type ... Package
* this is package ‘VennDiagram’ version ‘1.6.23’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘VennDiagram’ can be installed ... OK
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking examples ... OK
* checking for unstated dependencies in ‘tests’ ... OK
* checking tests ... OK
  Running ‘test-all.R’
* checking PDF version of manual ... OK
* DONE
Status: OK
```

### CODE REVIEW

**Comment by tyamaguchi-ucla** [comment]
Nice! Can you add test results to the description to just make sure nothing is broken? As you're going to make multiple PRs for lintr issues, you may want to create a PR template for R packages based on the Nextflow pipeline PR template - https://github.com/uclahs-cds/template-NextflowPipeline/blob/main/.github/PULL_REQUEST_TEMPLATE.md

**Comment by dan-knight** [comment]
> Nice! Can you add test results to the description to just make sure nothing is broken? As you're going to make multiple PRs for lintr issues, you may want to create a PR template for R packages based on the Nextflow pipeline PR template - https://github.com/uclahs-cds/template-NextflowPipeline/blob/main/.github/PULL_REQUEST_TEMPLATE.md

I updated the PR description and included R CMD build/check results. Do you have any comments on this description format? I think it might be better to reduce R CMD check results to one of the checkboxes in future, but I felt it was useful to include the full log here.

**Comment by tyamaguchi-ucla** [comment]
> > Nice! Can you add test results to the description to just make sure nothing is broken? As you're going to make multiple PRs for lintr issues, you may want to create a PR template for R packages based on the Nextflow pipeline PR template - https://github.com/uclahs-cds/template-NextflowPipeline/blob/main/.github/PULL_REQUEST_TEMPLATE.md
> 
> I updated the PR description and included R CMD build/check results. Do you have any comments on this description format? I think it might be better to reduce R CMD check results to one of the checkboxes in future, but I felt it was useful to include the full log here.

Great. Yup, I think we can add one more checkbox for the full log as you mentioned and include the full log as you did for now.

**Review by tyamaguchi-ucla — APPROVED** [review]
Looks good to me. Anything to add @aholmes @bugh1 @stefaneng in terms of the lintr cleaning up process?

**Pull request merged**
